# Generated by Django 3.2.2 on 2021-05-12 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_1', models.TextField()),
                ('description_2', models.TextField()),
                ('image', models.ImageField(upload_to='About/')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=100)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greetings', models.CharField(max_length=55)),
                ('name', models.CharField(max_length=55)),
                ('title', models.CharField(max_length=55)),
                ('logo', models.CharField(max_length=2)),
                ('image', models.ImageField(upload_to='Home/')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=30)),
                ('description_1', models.CharField(max_length=120)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='Testimonial/')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('percent', models.CharField(max_length=3)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portfolio.about')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('link', models.URLField()),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portfolio.about')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('portfolio_type', models.CharField(max_length=55)),
                ('description', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='Portfolio/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('client', models.CharField(max_length=45)),
                ('tools', models.CharField(max_length=45)),
                ('website', models.URLField(blank=True, null=True)),
                ('complete_date', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portfolio.category')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Portfolio/')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portfolio.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=55)),
                ('title', models.CharField(max_length=55)),
                ('company', models.CharField(max_length=55)),
                ('description_1', models.CharField(max_length=60)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portfolio.about')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=55)),
                ('certificate', models.CharField(max_length=55)),
                ('description_1', models.CharField(max_length=95)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portfolio.about')),
            ],
        ),
    ]
