# Generated by Django 3.2.3 on 2021-05-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0003_auto_20210513_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('subject', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=35)),
                ('message', models.TextField()),
            ],
        ),
    ]
