# Generated by Django 3.2.3 on 2021-05-15 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0004_contactus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='portfolio',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Portfolio.gallery'),
            preserve_default=False,
        ),
    ]
