# Generated by Django 3.2.3 on 2021-06-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0006_auto_20210515_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'CONTACT US', 'verbose_name_plural': 'CONTACT US'},
        ),
        migrations.AddField(
            model_name='contactus',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
