# Generated by Django 3.2.4 on 2021-06-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0009_about_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='tools',
            new_name='backend',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='frontend',
            field=models.CharField(default='', max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='description_1',
            field=models.CharField(max_length=130),
        ),
    ]
